### ISSUE TITLE
WeatherStack API historical feature is not available for free plan

### ISSUE THREAD

**Issue by wslabosz** [goodylabs/FE-Zeus-dev-test#1]
Hello,

I would like to raise an issue with obligatory service to use (weather stack).
One of the main features of the application is a historical weather data showcase and that kind of API feature in weather stack is possible ONLY in paid subscription (9,99$ monthly). Moreover free plan only provides 250 calls monthly (which is kinda restricting but doable).

Should we try to find free API providing the same data or will you change the requirements for the application?

Thanks in advance!

**Comment by grzegorzblaszczyk** [comment]
@krisldz Can you reply to this one please?

**Comment by krisldz** [comment]
@wslabosz you are absolutely right, I've missed that. Let's use https://openweathermap.org/api  there's 5 days history in a free plan. Thanks
